EWC_NSAA/EWC_NSAA/Models/NavigatorLanguages.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace EWC_NSAA.Models
{
    public class NavigatorLanguages
    {
        public int NavigatorLanguageID { get; set; }
        public int FK_NavigatorID { get; set; }
        public int LanguageCode { get; set; }
        public string LanguageName { get; set; }
        public int SpeakingScore { get; set; }
        public int ListeningScore { get; set; }
        public int ReadingScore { get; set; }
        public int WritingScore { get; set; }
        public string xtag { get; set; }
        public System.DateTime DateCreated { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> LastUpdated { get; set; }
        public string UpdatedBy { get; set; }
    }
}

EWC_NSAA/EWC_NSAA/Models/Race.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace EWC_NSAA.RaceCBL.Models
{
    public class Race
    {
        //Integer value of a checkbox
        public int RaceCode { get; set; }

        //String name of a checkbox
        public string RaceName { get; set; }

        //Boolean value to select a checkbox
        //on the list
        public bool IsSelected { get; set; }

        //Object of html tags to be applied
        //to checkbox, e.g.:'new{tagName = "tagValue"}'
        public object Tags { get; set; }


    }
}

EWC_NSAA/EWC_NSAA/ViewModels/BarrierViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using EWC_NSAA.Models;
using System.Web.Mvc;

namespace EWC_NSAA.ViewModels
{
    public class BarrierViewModel
    {
        public tBarrier tBarrier { get; set; }
        public int? SelectedBarrierType { get; set; }
        public int? SelectedBarrier { get; set; }
        public string SelectedSolution { get; set; }
        public string SelectedFollowupDt { get; set; }
        public string SelectedImplementationStatus { get; set; }
        public List<tSolution> Solutions { get; set; }
        public List<trBarrier> trBarrier { get; set; }
        public int NSRecipientID { get; set; }
        public string RecipLastName { get; set; }
        public string RecipFirstName { get; set; }
        

    }
}

EWC_NSAA/EWC_NSAA/ViewModels/NavigatorTransferViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using EWC_NSAA.Models;

namespace EWC_NSAA.ViewModels
{
    public class NavigatorTransferViewModel
    {
        public int OldNavigatorID { get; set; }
        public int NewNavigatorID { get; set; }
        public int mode { get; set; }
        public DateTime NavigatorTransferDt { get; set; }
        public string NavigatorTransferReason { get; set; }
        public int NSRecipientID { get; set; }
        public string LastName { get; set; }
        public string FirstName { get; set; }
        public string Type { get; set; }
        public int Region { get; set; }
        public string RecipLastName { get; set; }
        public string RecipFirstName { get; set; }
        public string Language { get; set; }
        public string AgreeToSpeakEnglish { get; set; }
        public string Comments { get; set; }


    }
}

EWC_NSAA/EWC_NSAA/Controllers/BarriersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using EWC_NSAA.Models;
using EWC_NSAA.ViewModels;
using EWC_NSAA.Common;
using System.Web.Routing;

namespace EWC_NSAA.Controllers
{
    //[Authorize(Roles = @"EWC_NSAA_Contributors, EWC_NSAA_A")]
    public class BarriersController : BaseController
    {

        
             public ActionResult clinicalservices()
        {
            return View();
        }
        public ActionResult Assesment()
        {
            return View();
        }
        // GET: Barriers/Create
        public ActionResult Create()
        {
            BarrierViewModel BarrierVM = new BarrierViewModel();
            return PartialView("Create", BarrierVM);
        }

        // POST: Barriers/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(BarrierViewModel BarrierVM, int EncounterID) //[Bind(Include = "BarrierID,FK_EncounterID,BarrierType,BarrierAssessed,FollowUpDt,xtag,DateCreated,CreatedBy,LastUpdated,UpdatedBy")] tBarrier tBarrier)
        {
            var BarrierID = 0;

            tBarrier tBarrier = new tBarrier();
            tSolution tSolution = new tSolution();

            if (ModelState.IsValid)
            {

                try
                {
                    if (BarrierVM.SelectedBarrierType > 0)
                    {
                        //Create the tBarrier object
                        tBarrier.BarrierType = BarrierVM.SelectedBarrierType;
                        tBarrier.BarrierAssessed = BarrierVM.SelectedBarrier;
                        tBarrier.CreatedBy = "";
                        tBarrier.FK_EncounterID = EncounterID;
                        tBarrier.FollowUpDt = DateTime.MinValue;

                        //Insert Barrier and get Barrier ID
                        BarrierID = getProxy().InsertBarrier(EncounterID, tBarrier.BarrierType, tBarrier.BarrierAssessed, tBarrier.FollowUpDt);

                        string Solutions = BarrierVM.SelectedSolution;
                        string[] solutions = Solutions.Split(',');

                        string FollowupDt = BarrierVM.SelectedFollowupDt;
                        string[] followupdt = FollowupDt.Split(',');

                        string ImplementationStatus = BarrierVM.SelectedImplementationStatus;
                        string[] implementationstatus = ImplementationStatus.Split(',');


                        for (int i = 0; i < solutions.Count(); i++)
                        {
                            string sol = solutions[i].Substring(solutions[i].IndexOf(":") + 1);
                            string fup = followupdt[i].Substring(followupdt[i].IndexOf(":") + 1);
                            string imp = implementationstatus[i].Substring(implementationstatus[i].IndexOf(":") + 1);

                            if (sol != "") //Solution is checked
                            {

                                tSolution.SolutionOffered = Convert.ToInt32(sol);
                                if (fup != "")
                                { tSolution.FollowUpDt = Convert.ToDateTime(fup); }
                                else
                                { tSolution.FollowUpDt = DateTime.MinValue; }

                                tSolution.SolutionImplementationStatus = Convert.ToInt32(imp);

                                getProxy().InsertSolution(BarrierID, tSolution.SolutionOffered, tSolution.SolutionImplementationStatus, tSolution.FollowUpDt);
                            }
                        }
                    }

                }
                catch (System.Data.Entity.Validation.DbEntityValidationException e)
                {
                    foreach (var eve in e.EntityValidationErrors)
                    {
                        Console.WriteLine("Entity of type \"{0}\" in state \"{1}\" has the following validation errors:",
                            eve.Entry.Entity.GetType().Name, eve.Entry.State);
                        foreach (var ve in eve.ValidationErrors)
                        {
                            Console.WriteLine("- Property: \"{0}\", Error: \"{1}\"",
                                ve.PropertyName, ve.ErrorMessage);
                        }
                    }
                    throw; //Errors.PublishException(e, GetAppName(false), GetVersion());
                }

            }
            else
            {
                var allErrors = ModelState.Values.SelectMany(v => v.Errors);

            }


            //ViewBag.FK_EncounterID = new SelectList(db.tEncounter, "EncounterID", "EncounterStartTime", tBarrier.FK_EncounterID);
            return View(BarrierVM);
        }

        // GET: Barriers/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tBarrier tBarrier = GetBarrier((int)id);
            if (tBarrier == null)
            {
                return HttpNotFound();
            }

            BarrierViewModel BarrierVM = new BarrierViewModel();
            BarrierVM.tBarrier = tBarrier;

            BarrierVM.SelectedBarrierType = BarrierVM.tBarrier.BarrierType;
            BarrierVM.SelectedBarrier = BarrierVM.tBarrier.BarrierAssessed;
            
            try
            {
                List<tSolution> solutionsList = GetSolutionsFromDataSet(BarrierVM.tBarrier.BarrierID);
                BarrierVM.Solutions = solutionsList.ToList();
                if(BarrierVM.Solutions.Count > 0)
                {
                    foreach(tSolution solution in BarrierVM.Solutions)
                    {
                        if(solution.FollowUpDt == DateTime.MinValue)
                        {
                            solution.FollowUpDt = null;
                        }
                    }
                }
                

            }
            catch (Exception e)
            {
                throw; //Errors.PublishException(e, GetAppName(false), GetVersion());
            }

            return View(BarrierVM);
        }

        // POST: Barriers/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        public ActionResult Edit(BarrierViewModel BarrierVM)//[Bind(Include = "BarrierID,FK_EncounterID,BarrierType,BarrierAssessed,FollowUpDt,xtag,DateCreated,CreatedBy,LastUpdated,UpdatedBy")] tBarrier tBarrier)
        {
            var BarrierID = BarrierVM.tBarrier.BarrierID;

            tBarrier tBarrier = new tBarrier();
            tSolution tSolution = new tSolution();

            if (ModelState.IsValid)
            {
                
                try
                {
                    if (BarrierVM.SelectedBarrierType > 0)
                    {
                        //Create the tBarrier object
                        tBarrier.BarrierType = BarrierVM.SelectedBarrierType;
                        tBarrier.BarrierAssessed = BarrierVM.SelectedBarrier;
                        tBarrier.CreatedBy = "";
                        tBarrier.FK_EncounterID = BarrierVM.tBarrier.FK_EncounterID;
                        tBarrier.FollowUpDt = DateTime.MinValue;


                        //Update Barrier
                        getProxy().UpdateBarrier(BarrierID, tBarrier.FK_EncounterID, tBarrier.BarrierType, tBarrier.BarrierAssessed, tBarrier.FollowUpDt);

                        string Solutions = BarrierVM.SelectedSolution;
                        string[] solutions = Solutions.Split(',');

                        string FollowupDt = BarrierVM.SelectedFollowupDt;
                        string[] followupdt = FollowupDt.Split(',');

                        string ImplementationStatus = BarrierVM.SelectedImplementationStatus;
                        string[] implementationstatus = ImplementationStatus.Split(',');

                        //Remove all Solutions for this barrier before adding 
                        int retVal = getProxy().DeleteSolutions(BarrierID);

                        for (int i = 0; i < solutions.Count(); i++)
                        {
                            string sol = solutions[i].Substring(solutions[i].IndexOf(":") + 1);
                            string fup = followupdt[i].Substring(followupdt[i].IndexOf(":") + 1);
                            string imp = implementationstatus[i].Substring(implementationstatus[i].IndexOf(":") + 1);

                            if (sol != "") //Solution is checked
                            {

                                tSolution.SolutionOffered = Convert.ToInt32(sol);
                                if (fup != "")
                                { tSolution.FollowUpDt = Convert.ToDateTime(fup); }
                                else
                                { tSolution.FollowUpDt = DateTime.MinValue; }

                                tSolution.SolutionImplementationStatus = Convert.ToInt32(imp);

                                getProxy().InsertSolution(BarrierID, tSolution.SolutionOffered, tSolution.SolutionImplementationStatus, tSolution.FollowUpDt);
                            }
                        }

                    }

                }
                catch (System.Data.Entity.Validation.DbEntityValidationException e)
                {
                    foreach (var eve in e.EntityValidationErrors)
                    {
                        Console.WriteLine("Entity of type \"{0}\" in state \"{1}\" has the following validation errors:",

EWC_NSAA/EWC_NSAA/Views/Shared/_BarrierList.cshtml
@*@model EWC_NSAA.ViewModels.EncounterViewModel

@{
    Layout = null;
}

<table class="table">
    <tr>
        <th>
            @Html.LabelFor(model => model.BarrierList.FirstOrDefault().BarrierType)
        </th>
        <th>
            @Html.LabelFor(model => model.BarrierList.FirstOrDefault().BarrierAssessed)
        </th>
        <th>
            @Html.LabelFor(model => model.BarrierList.FirstOrDefault().DateCreated)
        </th>
        <th>
            @Html.LabelFor(model => model.BarrierList.FirstOrDefault().CreatedBy)
        </th>
        <th>
            @Html.LabelFor(model => model.BarrierList.FirstOrDefault().LastUpdated)
        </th>
        <th>
            @Html.LabelFor(model => model.BarrierList.FirstOrDefault().UpdatedBy)
        </th>

        <th></th>
    </tr>

    @foreach (var item in Model.BarrierList)
    {
        <tr>
            <td>
                @Model.BarrierTypes.Where(x => x.BarrierTypeCode == item.BarrierType).Select(x => x.BarrierTypeDescription).First()
            </td>
            <td>
                @Model.Barriers.Where(x => x.BarrierCode == item.BarrierAssessed).Select(x => x.BarrierDescription).First()
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DateCreated)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CreatedBy)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.LastUpdated)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.UpdatedBy)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", "Barriers", new { id = item.BarrierID }, null)
            </td>
        </tr>

    }

</table>*@

EWC_NSAA/EWC_NSAA/Views/Shared/_Demographics.cshtml
@model EWC_NSAA.ViewModels.RecipientViewModel

<div class="row">
    <div class="col-md-4">
        <div class="form-group">
            @Html.LabelFor(model => model.tServiceRecipient.ImmigrantStatus, "New Immigrant", htmlAttributes: new { @class = "control-label col-md-5" })
            <div class="col-md-offset-5">
                <div class="checkbox">
                    @Html.EditorFor(model => model.tServiceRecipient.ImmigrantStatus)
                    @Html.ValidationMessageFor(model => model.tServiceRecipient.ImmigrantStatus, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>
    </div>
    <div class="col-md-4">
        <div class="form-group">
            @Html.LabelFor(model => model.tServiceRecipient.CountryOfOrigin, "Country of Origin", htmlAttributes: new { @class = "control-label col-md-5" })
            <div class="col-md-offset-5">
                @Html.DropDownListFor(model => model.tServiceRecipient.CountryOfOrigin, EWC_NSAA.Controllers.EnrollmentController.GetCountriesDropDown(), "--Select Country--")
                @Html.ValidationMessageFor(model => model.tServiceRecipient.CountryOfOrigin, "", new { @class = "text-danger" })
            </div>
        </div>

    </div>
    <div class="col-md-4">
        <div class="form-group">
            @Html.LabelFor(model => model.tServiceRecipient.Ethnicity, "Ethnicity", htmlAttributes: new { @class = "control-label col-md-5" })
            <div class="col-md-offset-5">
                
            <div class="radio-inline">
                @Html.CheckBox("ethnicity", "Hispanic", true, new { id = "Hispanic" }) Hispanic
            </div>
            <div class="radio-inline">
                @Html.RadioButton("ethnicity", "Non-Hispanic", new { id = "Non-Hispanic" }) Non-Hispanic
            </div>
            @Html.ValidationMessageFor(model => model.tServiceRecipient.Ethnicity, "", new { @class = "text-danger" })
                
            </div>
        </div>
    </div>
</div>


<div>
    @Html.HiddenFor(model => model.tServiceRecipient.Gender)
</div>

<div class="row">
    <div class="col-md-4">
        <div class="form-group">
            @Html.LabelFor(model => model.tServiceRecipient.PrimaryLanguage, "* Primary Language", htmlAttributes: new { @class = "control-label col-md-5" })
            <div class="col-md-offset-5">
                @Html.DropDownListFor(model => model.tServiceRecipient.PrimaryLanguage, EWC_NSAA.Controllers.EnrollmentController.GetLanguagesDropDown(), "--Select Language--")
                @Html.ValidationMessageFor(model => model.tServiceRecipient.PrimaryLanguage, "", new { @class = "text-danger" })
            </div>
        </div>
    </div>
    <div class="col-md-4">
        <div class="form-group">
            @Html.LabelFor(model => model.tServiceRecipient.AgreeToSpeakEnglish, "* Can effectively communicate in English?", htmlAttributes: new { @class = "control-label col-md-5" })
            <div class="col-md-offset-5">
                <div class="checkbox">
                    @Html.EditorFor(model => model.tServiceRecipient.AgreeToSpeakEnglish)
                    @Html.ValidationMessageFor(model => model.tServiceRecipient.AgreeToSpeakEnglish, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

    </div>
</div>


@section scripts {
    <script type="text/javascript">
    $(function () {

        $("input[name='ethnicity']").click(function () {

            if ($("#Hispanic").is(":checked")) {

                $("#Non-Hispanic").is(":unchecked");

            } else {

                $("#Hispanic").is(":unchecked");

            }

        });

    });
    </script>
}

 

EWC_NSAA/EWC_NSAA/Views/Shared/_EncounterDetails.cshtml
@using MvcCheckBoxList.Model
@model EWC_NSAA.ViewModels.EncounterViewModel
@{
    Layout = null;
}

<div class="panel panel-default" style="border:none;margin-top: -10px;" id="">

    <h3 style="padding-left:17px"><b> Encounter </b></h3>
    <br />
    <div class="panel-body" style="margin-bottom: -20px;">

        <div class="row">
            <div class="col-md-2">
                <div class="form-group">
                    @Html.LabelFor(model => model.tEncounter.EncounterID, "NSR ID")
                    @Html.EditorFor(model => model.tEncounter.FK_RecipientID, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.tEncounter.FK_RecipientID, "", new { @class = "text-danger" })

                </div>
            </div>
        </div>
        <br />
        <div class="row">
            <div class="col-md-3">
                <div class="form-group">
                    @Html.LabelFor(model => model.tEncounter.EncounterNumber, "Encounter Number")<br />
                    @*<div class="col-md-offset-5">*@
                    <div class="col-md-5" style="margin-left:-12px">
                        @Html.EditorFor(model => model.tEncounter.EncounterNumber, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.tEncounter.EncounterNumber, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>
            @*<div class="col-md-1"></div>*@
            <div class="col-md-2">
                <div class="form-group">
                    @Html.LabelFor(model => model.tEncounter.EncounterType, "Encounter Type")
                    @Html.DropDownListFor(model => model.tEncounter.EncounterType, EWC_NSAA.Controllers.EnrollmentController.GetCaregiverContactPrefDropDown(), "Select Encounter Type", new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.tEncounter.EncounterType, "", new { @class = "text-danger" })
                    @*</div>*@
                </div>
            </div>
            <div class="col-md-1"></div>
            <div class="col-md-3">
                <div class="form-group">
                    <div class="col-md-10" style="margin-left:-10px;">
                        <label>Reason </label>
                        <select class="form-control">
                            <option value="" selected="selected">Select Reason</option>
                            <option value="1">Support</option>
                            <option value="2">Assesment</option>
                        </select>

                        </div>

                    </div>
            </div>
            @*<div class="col-md-1"></div>*@

            <div class="col-md-3">
                <span style="color:red;margin-left:-10px"> *</span>&nbsp;<label type="label">Missed Appointment  </label>
                <div class="form-group">
                    <label id="sliderLabel">
                        <input type="checkbox" onchange="missedAppointmentChange(this)" />
                        <span id="slider">
                            <span id="sliderOn">Yes</span>
                            <span id="sliderOff">No</span>
                            <span id="sliderBlock"></span>
                        </span>
                        @Html.HiddenFor(model => model.tEncounter.MissedAppointment, new { @id = "text-danger" })
                    </label>
                </div>
            </div>
        </div>
        <br />
        <div class="row">
            <div class="col-md-2">
                <div class="form-group">
                    @Html.LabelFor(model => model.tEncounter.EncounterDt, "Date")
                    <div class="input-group date" style="width:150px;">
                        <div class="input-group-addon">
                            <i class="fa fa-calendar"></i>
                        </div>
                        @Html.EditorFor(model => model.tEncounter.EncounterDt, new { htmlAttributes = new { @class = "form-control", id = "txtEncounterDate" } })
                        @*<input type="text" id="datereferral" class="form-control" placeholder="" autocomplete="off" style="height:38px">*@
                    </div>
                    @Html.ValidationMessageFor(model => model.tEncounter.EncounterDt, "", new { @class = "text-danger" })
                </div>
                @*</div>*@




            </div>
            <div class="col-md-1"></div>
            <div class="col-md-2">
                <div class="col-md-10" style="margin-left:-10px;">
                    <div class="form-group">
                        @Html.LabelFor(model => model.tEncounter.EncounterStartTime, " Start Time")
                        @*<div class="col-md-offset-5">*@
                        @Html.EditorFor(model => model.tEncounter.EncounterStartTime, new { htmlAttributes = new { @class = "form-control", @id="dvEncounterStartTime"} })
                        @Html.ValidationMessageFor(model => model.tEncounter.EncounterStartTime, "", new { @class = "text-danger" })
                        @*</div>*@
                    </div>
                    </div>
                </div>
            <div class="col-md-1"></div>
            <div class="col-md-2">
                <div class="col-md-10" style="margin-left:-10px;">
                    <div class="form-group">
                        @Html.LabelFor(model => model.tEncounter.EncounterEndTime, "End Time")
                        @*<div class="col-md-offset-5">*@
                        @Html.EditorFor(model => model.tEncounter.EncounterEndTime, new { htmlAttributes = new { @class = "form-control", @id = "dvEncounterEndTime" } })
                        @Html.ValidationMessageFor(model => model.tEncounter.EncounterEndTime, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </div>
        </div>
        <br />
        <div class="row">






            <div class="col-md-2">

                <label>Goal</label>
                <div class="form-group">


                    <select class="form-control">
                        <option value="" selected="selected">Select Goal</option>
                        <option value="1">SN</option>

                        <option value="2">CMN</option>
                        <option value="2">TRFN</option>
                    </select>



                </div>
                @*<div class="form-group">
                        <label>Goal</label>

                        @Html.DropDownListFor(model => model.tEncounter.EncounterType, EWC_NSAA.Controllers.EncountersController.GetSvcOutcomeStatusDropDown(), "--Select Outcome Status--", new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.tEncounter.SvcOutcomeStatus, "", new { @class = "text-danger" })

                    </div>*@
            </div>
            <div class="col-md-1"></div>
            <div class="col-md-3">
                <div class="col-md-10" style="margin-left:-10px;">
                    <div class="form-group">
                        @Html.LabelFor(model => model.tEncounter.SvcOutcomeStatus, "Acheived Goal")

                        @Html.DropDownListFor(model => model.tEncounter.EncounterType, EWC_NSAA.Controllers.EncountersController.GetSvcOutcomeStatusDropDown(), "Select  Status", new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.tEncounter.SvcOutcomeStatus, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </div>
            @*<div class="col-md-1"></div>*@
            <div class="col-md-4">
                <div class="form-group">
                    @Html.LabelFor(model => model.tEncounter.EncounterReason, "Reason Goal Not Acheived")
                    @Html.EditorFor(model => model.tEncounter.ServicesTerminatedReason, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.tEncounter.EncounterReason, "", new { @class = "text-danger" })

                </div>

            </div>
        </div>
        <br />

    </div>
    <div class="panel-footer" style="border-top: none;">
        <div class="row">
            <div class="col-md-9"></div>
            <div class="col-md-3 pull-left">
                <a href="#" class="btn btn-success" style="background-color: #3a3a3a;border: 2px #cfcfcf;font-size: 18px !important;" id="activate-step"> &nbsp;&nbsp;&nbsp;Save&nbsp;&nbsp;&nbsp;</a>
                <a onclick="showHideTab('two')" class="btn" id="back-step" style="cursor:pointer;background-color: #3a3a3a;border: 2px #cfcfcf;font-size: 18px !important;color: #fff;">  &nbsp;&nbsp;&nbsp; Next <span class="glyphicon glyphicon-arrow-right"></span>&nbsp;&nbsp;  </a>

            </div>

        </div>
        @*<div class="row">
            <div class="col-md-9"></div>
            <div class="col-md-3 pull-right">
                <a href="#" class="btn btn-success" style="background-color: #3a3a3a;border: 2px #cfcfcf;font-size: 18px !important;" id="activate-step"> &nbsp;&nbsp;&nbsp;Save&nbsp;&nbsp;&nbsp;</a>

                <a onclick="showHideTab('two')" class="btn" id="back-step" style="cursor:pointer;background-color: #3a3a3a;border: 2px #cfcfcf;font-size: 18px !important;color: #fff;">  Next &gt;&gt; </a>
            </div>
        </div>*@

    </div>
</div>

<script>
    $('#txtEncounterDate').datepicker().on('txtEncounterDate', function (ev) {

 });
</script>

EWC_NSAA/EWC_NSAA/Views/Shared/_Notes.cshtml
@using MvcCheckBoxList.Model
@model EWC_NSAA.ViewModels.EncounterViewModel

@{
    Layout = null;
}


<div class="panel panel-default" style="border:none">
    <h3 style="padding-left:25px"><b>Notes</b></h3>
    <div class="panel-body">

        <div class="row">
            <div class="col-md-12">
                <div style="float:left;width:1000px;">
                    <textarea id="textarea" style="margin: 0px; width: 1000px; height: 100px;"></textarea>
                </div>
            </div>
        </div>

        <br />
        <label style="padding-left:20px"><b>Previous Notes</b></label>
        <div class="row">
            <div class="col-md-12">
                <div style="float:left;width:1000px;">
                    <textarea id="textarea" style="margin: 0px; width: 1000px; height: 200px;" readonly="readonly" disabled="disabled"></textarea>
                </div>
            </div>
        </div>
    </div>
    <div class="panel-footer" style="border-top:none;">
        <div class="row">
            <div class="col-md-9"></div>
            <div class="col-md-3 pull-left">

                <a onclick="showHideTab('three')" class="btn" id="back-step" style="cursor:pointer;background-color: #3a3a3a;border: 2px #cfcfcf;font-size: 18px !important;color: #fff;"> <span class="glyphicon glyphicon-arrow-left"></span>  Previous   </a>
                <a href="#" class="btn btn-success" style="background-color: #3a3a3a;border: 2px #cfcfcf;font-size: 18px !important;" id="activate-step"> &nbsp;&nbsp;&nbsp;Save&nbsp;&nbsp;&nbsp;</a>
            </div>

        </div>
    </div>
</div>