EWC_NSAA/EWC_NSAA/Controllers/EnrollmentController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using EWC_NSAA.Models;
using EWC_NSAA.RaceCBL.Models;
using EWC_NSAA.ViewModels;
using System.Collections;
using System.Data.Entity.Core.Objects;
using System.Data.Entity.Infrastructure;
using EWC_NSAA.Common;
using EWC_NSAA.CaregiverApprovalCBL.Models;

// For using NavigationCycle ViewModels functions
using EWC_NSAA.ContactPreferenceCBL.Models;

namespace EWC_NSAA.Controllers
{
    //[Authorize(Roles = @"EWC_NSAA_Contributors, EWC_NSAA_A")]
    public class EnrollmentController : BaseController
    {        
        // GET: Enrollment
        public ActionResult Index()
        {
            RecipientListViewModel RecipVM = new RecipientListViewModel();            
            List<trProvLanguages> lsLanguages = new List<trProvLanguages>();
            List<tServiceRecipient> lsRecipients = new List<tServiceRecipient>();

            try
            {
                lsLanguages = GetLanguagesFromDataSet();
                lsRecipients = GetRecipientsFromDataSet();

                RecipVM.Languages = lsLanguages;
                RecipVM.Recipients = lsRecipients;
            }
            catch (Exception e)
            {
                throw; //Errors.PublishException(e, GetAppName(false), GetVersion());
            }
            
            return View(RecipVM);
        }

        public ActionResult ViewEnrolledRecipient()
        {
            RecipientListViewModel RecipVM = new RecipientListViewModel();
            List<tServiceRecipient> lsRecipients = new List<tServiceRecipient>();

            try
            {
                lsRecipients = GetRecipientsFromDataSet();
                RecipVM.Recipients = lsRecipients;

            }
            catch (Exception e)
            {
                throw; //Errors.PublishException(e, GetAppName(false), GetVersion());
            }

            return View(RecipVM);
        }
        
        // GET: Enrollment/Create        
        public ActionResult Create()
        {
            tServiceRecipient tservicerecipient = new tServiceRecipient();
            var tservicerecipientVM = new RecipientViewModel();
                        
            //Race setup
            var selectedRace = new List<Race>();

            //Caregiver Approval setup
            var selectedCaregiverApproval = new List<CaregiverApprovals>();

            var tNSProvider = new tNSProvider();
            var selectedWeekday = new List<WeekdayContactPreference>();
            var selectedTime = new List<TimeContactPreference>();

            try
            {
                tservicerecipientVM.AvailableRace = GetAll().ToList();
                tservicerecipientVM.SelectedRace = selectedRace;

                tservicerecipientVM.AvailableApprovals = GetAllApprovals().ToList();
                tservicerecipientVM.SelectedApprovals = selectedCaregiverApproval;
               
                //Defaut State to CA
                tservicerecipient.State = "CA";

                tservicerecipientVM.tServiceRecipient = tservicerecipient;

                if (tservicerecipientVM.tServiceRecipient.DOB == DateTime.MinValue)
                {
                    tservicerecipientVM.tServiceRecipient.DOB = null;
                }

                tservicerecipientVM.AvailableWeekday = GetAllWeekdays().ToList();
                tservicerecipientVM.SelectedWeekday = selectedWeekday;

                //Time setup
                tservicerecipientVM.AvailableTime = GetAllTimes().ToList();
                tservicerecipientVM.SelectedTime = selectedTime;

                tNSProvider.NSProviderID = 0;
                tservicerecipientVM.tNSProvider = tNSProvider;


            }
            catch (Exception e)
            {
                throw; //Errors.PublishException(e, GetAppName(false), GetVersion());
            }

            return View(tservicerecipientVM);
        }

        // POST: Enrollment/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]       
        public ActionResult Create([Bind (Exclude="RaceID")] RecipientViewModel RecipVM)//[Bind(Include = "FK_RecipID,LastName,FirstName,MiddleInitial,DOB,AddressNotAvailable,Address1,Address2,City,State,Zip,Phone1,P1PhoneType,P1PhoneTypeOther,P1PersonalMessage,Phone2,P2PhoneType,P2PhoneTypeOther,P2PersonalMessage,MotherMaidenName,Email,SSN,ImmigrantStatus,CountryOfOrigin,Gender,Race1,Race1Other,Race2,Ethnicity,PrimaryLanguage,AgreeToSpeakEnglish,CaregiverName,Relationship,RelationshipOther,CaregiverPhone,CaregiverPhoneType,CaregiverPhoneTypeOther,CaregiverPhonePersonalMessage,CaregiverEmail,CaregiverContactPreference,Comments")] RecipientViewModel Test)
        {
              
            int NSID = 0;
            int NavigatorID = 0;

            if (ModelState.IsValid)
            {
                //Race 
                var RaceList = GetRaceList(RecipVM);
                //Caregiver Approval
                var ApprovalList = GetCaregiverApprovalList(RecipVM);

                RecipVM.tServiceRecipient.CreatedBy = "";

                try
                {
                    RecipVM.tServiceRecipient.FK_NavigatorID = GetNavigatorID(); //NavigatorVM.tNavigator.NavigatorID;
                    NavigatorID = GetNavigatorID();
                }
                catch (Exception e)
                {
                    throw; //Errors.PublishException(e, GetAppName(false), GetVersion());
                }
                

                try
                {
                        int retValue = getProxy().InsertServiceRecipient(RecipVM.tServiceRecipient.FK_NavigatorID, 
                        RecipVM.tServiceRecipient.FK_RecipID, 
                        RecipVM.tServiceRecipient.LastName, 
                        RecipVM.tServiceRecipient.FirstName, 
                        RecipVM.tServiceRecipient.MiddleInitial,
                        RecipVM.tServiceRecipient.DOB,
                        RecipVM.tServiceRecipient.AddressNotAvailable, 
                        RecipVM.tServiceRecipient.Address1, 
                        RecipVM.tServiceRecipient.Address2, 
                        RecipVM.tServiceRecipient.City, 
                        RecipVM.tServiceRecipient.State, 
                        RecipVM.tServiceRecipient.Zip,
                        RecipVM.tServiceRecipient.Phone1, 
                        RecipVM.tServiceRecipient.P1PhoneType, 
                        RecipVM.tServiceRecipient.P1PersonalMessage, 
                        RecipVM.tServiceRecipient.Phone2, 
                        RecipVM.tServiceRecipient.P2PhoneType, 
                        RecipVM.tServiceRecipient.P2PersonalMessage,
                        RecipVM.tServiceRecipient.MotherMaidenName, 
                        RecipVM.tServiceRecipient.Email, 
                        RecipVM.tServiceRecipient.SSN, 
                        RecipVM.tServiceRecipient.ImmigrantStatus, 
                        RecipVM.tServiceRecipient.CountryOfOrigin, 
                        RecipVM.tServiceRecipient.Gender,
                        RecipVM.tServiceRecipient.Ethnicity,
                        RecipVM.tServiceRecipient.PrimaryLanguage, 
                        RecipVM.tServiceRecipient.AgreeToSpeakEnglish, 
                        RecipVM.tServiceRecipient.CaregiverName, 
                        RecipVM.tServiceRecipient.Relationship, 
                        RecipVM.tServiceRecipient.RelationshipOther,
                        RecipVM.tServiceRecipient.CaregiverPhone, 
                        RecipVM.tServiceRecipient.CaregiverPhoneType, 
                        RecipVM.tServiceRecipient.CaregiverPhonePersonalMessage, 
                        RecipVM.tServiceRecipient.CaregiverEmail, 
                        RecipVM.tServiceRecipient.CaregiverContactPreference, 
                        RecipVM.tServiceRecipient.Comments);

                    NSID = retValue;

                    if(RecipVM.tRace.RaceOther == null)
                    {
                        RecipVM.tRace.RaceOther = "";
                    }
                    getProxy().SaveRace(NSID, RaceList, RecipVM.tRace.RaceOther);

                    if(RecipVM.tCaregiverApprovals == null)
                    {
                        tCaregiverApprovals tCaregiverApprovals = new tCaregiverApprovals();
                        RecipVM.tCaregiverApprovals = tCaregiverApprovals;
                    }

                    if (RecipVM.tCaregiverApprovals.CaregiverApprovalOther == null)
                    {
                        RecipVM.tCaregiverApprovals.CaregiverApprovalOther = "";
                    }
                    getProxy().SaveCaregiverApproval(NSID, ApprovalList, RecipVM.tCaregiverApprovals.CaregiverApprovalOther);

                    // Calling a new Local Function
                    Save(RecipVM, NSID, NavigatorID);

                    TempData["FeedbackMessage"] = "Your changes were saved successfully.";
                }
                catch (System.Data.Entity.Validation.DbEntityValidationException e)
                {
                    foreach (var eve in e.EntityValidationErrors)
                    {
                        Console.WriteLine("Entity of type \"{0}\" in state \"{1}\" has the following validation errors:",
                            eve.Entry.Entity.GetType().Name, eve.Entry.State);
                        foreach (var ve in eve.ValidationErrors)
                        {
                            Console.WriteLine("- Property: \"{0}\", Error: \"{1}\"",
                                ve.PropertyName, ve.ErrorMessage);
                        }
                    }

EWC_NSAA/EWC_NSAA/Views/Enrollment/Edit.cshtml
@using MvcCheckBoxList.Model
@model EWC_NSAA.ViewModels.RecipientViewModel

@{
    ViewBag.Title = "Edit";
}
<head>
    <link href='https://fonts.googleapis.com/css?family=Fira Sans' rel='stylesheet'>
    <link href="~/Content/style.css" rel="stylesheet" />
    <link href="~/Content/custom.css" rel="stylesheet" />
</head>

<div class="row col-md-12">
    <!-- widget content -->
    <div class="widget-body margin24">
        <div class="row">
            <form id="wizard-1" novalidate="novalidate">
                <div id="bootstrap-wizard-1" class="col-sm-12">
                    <div class="form-bootstrapWizard">
                        <ul class="bootstrapWizard form-wizard col-md-offset-1" style="padding-left:50px;">
                            <li class="active" data-target="#step1">
                                <a onclick="return showHideTab('one')" data-toggle="tab" class="active" style="cursor:pointer"> <span class="step">1</span> <span class="title">Recipient <br /><br />Information</span> </a>
                            </li>
                            <li data-target="#step2" class="">
                                <a onclick="return showHideTab('two','two')" data-toggle="tab" style="cursor:pointer"> <span class="step">2</span> <span class="title">Referral<br /><br /> Information</span> </a>
                            </li>
                            <li data-target="#step3" class="">
                                <a onclick="return showHideTab('three','three')" data-toggle="tab" style="cursor:pointer"> <span class="step">3</span> <span class="title">Provider <br /><br />Information</span> </a>
                            </li>
                            <li data-target="#step4">
                                <a onclick="return showHideTab('four','four')" data-toggle="tab" style="cursor:pointer"> <span class="step">4</span> <span class="title">Contact <br /><br />Preferences</span> </a>
                            </li>
                            <li data-target="#step5">
                                <a onclick="return showHideTab('five','five')" data-toggle="tab" style="cursor:pointer"> <span class="step">5</span> <span class="title">Additional /<br /><br />Caregiver<br /><br /> Contact</span> </a>
                            </li>
                            <li data-target="#step6">
                                <a onclick="return showHideTab('six','six')" data-toggle="tab" style="cursor:pointer"> <span class="step">6</span> <span class="title"> Notes</span> </a>
                            </li>
                        </ul>
                        <div class="clearfix"></div>
                    </div>
                    <br />
                    <div class="tab-content">
                        <div class="panel panel-default margin30" id="tab1">
                            <div class="panel-body  col-md-12" style="border: none; margin-bottom: -15px;">

                                <div class="tab-pane active">
                                    @Html.Partial("_PersonalInfo", Model)
                                </div>
                            </div>
                        </div>
                        <div class="panel panel-default margin30" id="tab2">
                            <div class="panel-body  col-md-12" style="border: none; margin-bottom: -15px;">
                                <div class="tab-pane">
                                    @Html.Partial("_ReferralInfo", Model)
                                </div>
                            </div>
                        </div>
                        <div class="panel panel-default margin30" id="tab3">
                            <div class="panel-body  col-md-12" style="border: none; margin-bottom: -15px;">
                                <div class="tab-pane">
                                    @Html.Partial("_NSProvider", Model)
                                </div>
                            </div>
                        </div>
                        <div class="panel panel-default margin30" id="tab4" style="border: none; margin-bottom: -15px;">
                            <div class="panel-body col-md-12">
                                <div class="tab-pane">

                                    @Html.Partial("Ns_Enrollment_tab4", Model)
                                </div>
                            </div>
                        </div>
                        <div class="panel panel-default margin30" id="tab5" style="border: none; margin-bottom: -15px;">
                            <div class="panel-body col-md-12">
                                <div class="tab-pane">
                                    @Html.Partial("Ns_Enrollment_tab5", Model)
                                </div>
                            </div>
                        </div>
                        <div class="panel panel-default margin30" id="tab6" style="border: none; margin-bottom: -15px;">
                            <div class="panel-body col-md-12">
                                <div class="tab-pane">
                                    @Html.Partial("Ns_Enrollment_tab6", Model)
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
    <!-- end widget content -->

</div>
<script>
    $(document).ready(function () {
        $('#tab2').css('display', 'none');
        $('#tab3').css('display', 'none');
        $('#tab4').css('display', 'none');
        $('#tab5').css('display', 'none');
        $('#tab6').css('display', 'none');
        $('#txtDateofBirth').datepicker().on('changeDate', function (ev) {
            $('li.active').addClass('halfactive');
            $('li.active').removeClass('active');
        });
    })

    $("input[type='text']").keyup(function (e) {
        if (e.target.value != "") {
            $('li.active').addClass('halfactive')
            $('li.active').removeClass('active')
            $(e.target).css('border-color', '');
        }
        else {
            $('li.halfactive').addClass('active')
            $('li.halfactive').removeClass('halfactive')
        }
    });

    function showHideTab(currentTab, previous) {
        if (validateForm(currentTab, previous)) {
            if (currentTab == "one") {
                $('#tab1').css('display', 'block');
                $('#tab2').css('display', 'none');
                $('#tab3').css('display', 'none');
                $('#tab4').css('display', 'none');
                $('#tab5').css('display', 'none');
                $('#tab6').css('display', 'none');
            }
            else if (currentTab == "two") {
                $('#tab1').css('display', 'none');
                $('#tab2').css('display', 'block');
                $('#tab3').css('display', 'none');
                $('#tab4').css('display', 'none');
                $('#tab5').css('display', 'none');
                $('#tab6').css('display', 'none');
            }
            else if (currentTab == "three") {
                $('#tab1').css('display', 'none');
                $('#tab2').css('display', 'none');
                $('#tab3').css('display', 'block');
                $('#tab4').css('display', 'none');
                $('#tab5').css('display', 'none');
                $('#tab6').css('display', 'none');
            }
            else if (currentTab == "four") {
                $('#tab1').css('display', 'none');
                $('#tab2').css('display', 'none');
                $('#tab3').css('display', 'none');
                $('#tab4').css('display', 'block');
                $('#tab5').css('display', 'none');
                $('#tab6').css('display', 'none');
            }
            else if (currentTab == "five") {
                $('#tab1').css('display', 'none');
                $('#tab2').css('display', 'none');
                $('#tab3').css('display', 'none');
                $('#tab4').css('display', 'none');
                $('#tab5').css('display', 'block');
                $('#tab6').css('display', 'none');
            }
            else if (currentTab == "six") {
                $('#tab1').css('display', 'none');
                $('#tab2').css('display', 'none');
                $('#tab3').css('display', 'none');
                $('#tab4').css('display', 'none');
                $('#tab5').css('display', 'none');
                $('#tab6').css('display', 'block');
            }
            else if (currentTab == "demo") {
                $('#tab1').css('display', 'block');
                $('#tab2').css('display', 'none');
                $('#tab3').css('display', 'none');
                $('#tab4').css('display', 'none');
                $('#tab5').css('display', 'none');
                $('#tab6').css('display', 'none');
                $('#demographic').css('display', 'block');
                $('#personalInfo').css('display', 'none');
            }
            else if (currentTab == "personalInfo") {
                $('#tab1').css('display', 'block');
                $('#tab2').css('display', 'none');
                $('#tab3').css('display', 'none');
                $('#tab4').css('display', 'none');
                $('#tab5').css('display', 'none');
                $('#tab6').css('display', 'none');
                $('#demographic').css('display', 'none');
                $('#personalInfo').css('display', 'block');
            }

            else if (currentTab == "provider") {
                $('#tab1').css('display', 'none');
                $('#tab2').css('display', 'none');
                $('#tab3').css('display', 'block');
                $('#tab4').css('display', 'none');
                $('#tab5').css('display', 'none');
                $('#tab6').css('display', 'none');
                $('#provider').css('display', 'block');
                $('#healthcare').css('display', 'none');
            }

            else if (currentTab == "healthcare") {
                $('#tab1').css('display', 'none');
                $('#tab2').css('display', 'none');
                $('#tab3').css('display', 'block');
                $('#tab4').css('display', 'none');
                $('#tab5').css('display', 'none');
                $('#tab6').css('display', 'none');
                $('#provider').css('display', 'none');
                $('#healthcare').css('display', 'block');
            }

        }

    }

    function validateForm(currText, previous) {
        var tabVal = "";
        if (previous != undefined) {
            currText = previous;
        }
        if (currText == "one") {
            tabVal = "#step1";
        }
        else if (currText == "two") {
            tabVal = "#step2";
        }
        else if (currText == "three") {
            tabVal = "#step3";
        }
        else if (currText == "four") {
            tabVal = "#step4";
        }
        else if (currText == "five") {
            tabVal = "#step5";
        }
        else if (currText == "six") {
            tabVal = "#step6";
        }
        if (tabVal != "") {
            setSelected(tabVal)
        }
        return true;
    }
    function setSelected(value) {
        $('.bootstrapWizard').find('li').each(function () {
            if ($(this).attr('data-target') == value) {
                $(this).addClass('halfactive');
                $(this).removeClass('active');
            }
            else {
                $(this).removeClass('active');
                $(this).removeClass('halfactive');
            }
        })
    }

    function validateControl(ctrlId) {
        if ($.trim($('#' + ctrlId).val()) == "") {
            $('#' + ctrlId).css('border-color', 'red');
            $('#' + ctrlId).focus();
            return false;
        }
        return true;
    }

</script>

EWC_NSAA/EWC_NSAA/Views/Enrollment/ViewEnrolledRecipient.cshtml
@using EWC_NSAA.ViewModels
@model RecipientListViewModel
@{
    ViewBag.Title = "ViewEnrolledRecipient";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<br />
<br />

<style type="text/css">
    .table {
        font-family: 'FiraSans-Light' !important;
        font-size: 18px !important;
        width: 100%;
        display: table;
        border-collapse: separate;
        border: solid 1px #000000 !important;
        background-color: white;
    }

    .table-header {
        font-family: 'FiraSans-Light' !important;
        font-size: 18px !important;
    }

    .webgrid-header a {
        text-decoration: none !important;
        font-family: 'FiraSans-Light' !important;
        font-size: 18px !important;
        color: white !important;
    }

    .table th {
        padding: 17px 6px 10px;
        text-align: center;
        align-items: center;
        font-family: 'FiraSans-Light' !important;
        font-size: 18px !important;
    }

    .table td {
        padding: 5px 2px 2px;
        text-align: center;
        align-items: center;
        font-family: 'FiraSans-Light' !important;
        font-size: 18px !important;
    }

    .table-header {
        background-color: #7EB2B2;
        color: white;
        padding-bottom: 2px;
        padding-top: 2px;
        font-family: 'FiraSans-Light' !important;
        font-size: 18px !important;
    }

    .table-footer {
    }

    .table-row-style {
        padding: 3px 7px 2px;
        text-align: center;
        font-family: 'FiraSans-Light' !important;
        font-size: 18px !important;
    }

    .table-alternating-row {
        background-color: #DEF9F9;
        padding: 3px 7px 2px;
        font-family: 'FiraSans-Light' !important;
        font-size: 18px !important;
    }

    .rating-star-block .star.outline {
        background: url("~/Images/star-empty-lg.png") no-repeat scroll 0 0 rgb(182, 255, 0);
    }

    .rating-star-block .star.filled {
        background: url("~/Images/star-fill-lg.png") no-repeat scroll 0 0 rgb(255, 106, 0);
    }

    .rating-star-block .star {
        color: rgb(255, 216, 0);
        display: inline-block;
        height: 24px;
        overflow: hidden;
        text-indent: -999em;
        width: 24px;
    }

    a {
        color: #005782;
        text-decoration: none;
    }

    table tr th {
        padding: 17px 5px 10px;
        text-align: center;
        background-color: #7EB2B2;
        align-items: center;
        font-family: 'FiraSans-Light' !important;
        font-size: 18px !important;
        color: #fff;
    }

    table tr td {
        padding: 5px 2px 2px;
        text-align: center;
        align-items: center;
        font-family: 'FiraSans-Light' !important;
        font-size: 18px !important;
    }

    .table-row-style {
        background-color: #DEF9F9;
        padding: 3px 7px 2px;
        text-align: center;
        font-family: 'FiraSans-Light' !important;
        font-size: 18px !important;
    }

    .table-striped > tbody > tr:nth-of-type(odd) {
        background-color: #DEF9F9;
        padding: 3px 7px 2px;
        font-family: 'FiraSans-Light' !important;
        font-size: 18px !important;
    }


    #Encountergrid .left {
        text-align: left;
    }

    #Encountergrid .center {
        text-align: center;
    }

    .dropdown-submenu {
        position: relative;
    }

        .dropdown-submenu .dropdown-menu {
            top: -1px;
            left: 50px;
            margin-top: -5px;
            z-index: 100;
            display: none;
        }

    .dropdown-menu {
        position: absolute;
        top: -1px;
        left: 100px;
        margin-top: -5px;
        z-index: 50;
        display: none;
    }
</style>

<div class="panel panel-default" style="border:none;margin-top: -10px;">
    <div class="panel-body" style="margin-bottom: -20px;">
        <div class="table-responsive" style="margin-top:-10px;padding-left:20px;">
            <table class="table table-hover table-striped" id="Encountergrid" style="width:80%;">
                <thead>
                    <tr>
                        <th>First Name</th>
                        <th>Last Name</th>
                        <th style="padding-left:10px;">NSR  ID</th>
                        <th>NSC</th>
                        <th>NSOS</th>
                        <th>Encounter</th>
                        <th>Action</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var obj in Model.Recipients)
            {
                        <tr>
                            <td class="left">@obj.FirstName</td>
                            <td class="left">@obj.LastName</td>
                            <td>@obj.NSRecipientID</td>
                            <td>@obj.NSRecipientID</td>
                            <td>
                                <a href="javascript:void(0);">
                                    @if (obj.NSRecipientID == 2)
                                    {
                                        <i class="fa fa-circle-thin  fa-1x"></i>
                                    }
                                    else if (obj.NSRecipientID == 3)
                                    {
                                        <i class="fa fa-check  fa-1x"></i>
                                    }
                                    else
                                    {
                                        <i class="fa fa-remove  fa-1x"></i>
                                    }
                                </a>
                            </td>
                            <td class="center">

                                <a href="@Url.Action("Create", "encounters",new { NSID = obj.NSRecipientID, NavigatorID = obj.FK_NavigatorID })" , onclick="navigationClick()">

                                    @if (obj.NSRecipientID == 1)
                                    {
                                        <i class="fa fa-circle  fa-2x" style="color:deepskyblue;"></i>
                                    }
                                    else
                                    {
                                        <i class="fa fa-circle  fa-2x" style="color:grey;"></i>
                                    }

                                </a>
                            </td>
                            <td>

                                <div class="dropdown">
                                    <button class="btn btn-default dropdown-toggle" type="button" data-toggle="dropdown">Actions</button>
                                    <ul class="ddlActions dropdown-menu">
                                        <li><a class="option" id="enrollment" tabindex="-1" href="#">Edit Enrollment</a></li>
                                        <li class="dropdown-submenu">
                                            <a class="option" id="encounter" href="#">Edit Encounter</a>
                                            <ul class="dropdown-menu">
                                                <li><a tabindex="-1" href="#">Enrollment 1</a></li>
                                                <li><a tabindex="-1" href="#">Enrollment 2</a></li>
                                                <li><a tabindex="-1" href="#">Enrollment 3</a></li>
                                            </ul>
                                        </li>
                                        <li><a class="option" id="transfer" tabindex="-1" href="#">Transfer</a></li>
                                    </ul>
                                </div>


                            </td>
                        </tr>
                    }

                </tbody>
            </table>
        </div>
    </div>
</div>

@section scripts
{
    <script type="text/javascript">
        $('div.dropdown>ul.ddlActions a').click(function () {
            var id = $(this).attr('id');

            if (id == "enrollment") {
                window.location = '@Url.Action("Create", "Enrollment",new { @Id="1" })'
            }
        });

        function navigationClick() {

            var location = window.location.href;

            if (location.toLocaleLowerCase().lastIndexOf('encounters') != -1) {
                $('#selectedHeading').css('background-color', '#2481c6');
                $('#selectedSpan').html('<font style="font-size:25px">Assesment</font>');
            }
        }



        $(document).ready(function () {

            var location = window.location.href;
            if (location.toLocaleLowerCase().lastIndexOf('encounters') != -1) {
                $('#selectedHeading').css('background-color', '#2481c6');
                $('#selectedSpan').html('Assesment');
            }

            $('.dropdown-submenu a.option').on("click", function (e) {
                $(this).next('ul').toggle();
                e.stopPropagation();
                e.preventDefault();
            });

        });
    </script>
}